name = "partyflare-example-remix"
main = "./dist/index.js"
compatibility_date = "2023-04-20"

assets = "public"

[define]
"process.env.REMIX_DEV_ORIGIN"= "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT"= "8002"
