name = "partyflare-example-remix"
main = "./dist/index.js"
compatibility_date = "2024-05-30"

assets = "public"

[define]
"process.env.REMIX_DEV_ORIGIN"= "'http://127.0.0.1:8002'"
"process.env.REMIX_DEV_SERVER_WS_PORT"= "8002"

[[durable_objects.bindings]]
name = "SessionStorage"
class_name = "SessionStorage"

[[durable_objects.bindings]]
name = "RemixServer"
class_name = "RemixServer"

[[durable_objects.bindings]]
name = "Tldraw"
class_name = "Tldraw"


 [[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SessionStorage", "RemixServer", "Tldraw"]
