name = "partyflare"
main = "src/index.ts"
compatibility_date = "2024-04-19"

assets = "public"


[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Chat"]