name = "partyflare-example-yjs"
main = "src/index.ts"
compatibility_date = "2024-04-19"

assets = "public"

[build]
command = "bun scripts/build.ts"
watch_dir = "client"


[[durable_objects.bindings]]
name = "Document"
class_name = "Document"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Document"]

